version: '1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  mongodb-primary:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - 'mongodb_master_data:/data/db'
    ports:
      - '27017:27017'

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    depends_on:
      - rabbitmq
      - mongodb-primary
      - product
      - cart
      - order
      - users
    volumes:
      - .:/usr/src/app # any chenge to the folder would be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev auth

  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: development
    env_file:
      - ./apps/product/.env
    depends_on:
      - rabbitmq
      - mongodb-primary
      - cart
      - order
      - users
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app # any chenge to the folder would be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev product

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    ports:
      - '3000:3000'
    env_file:
      - ./apps/users/.env
    depends_on:
      - rabbitmq
      - mongodb-primary
    volumes:
      - .:/usr/src/app # any chenge to the folder would be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev users

  order: 
    build: 
      context: .
      dockerfile: ./apps/order/Dockerfile
      target: development
    ports:
      - '3003:3003'
    env_file:
      - ./apps/order/.env
    depends_on:
      - rabbitmq
      - mongodb-primary
      - cart
      - users
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev order

  cart: 
    build: 
      context: .
      dockerfile: ./apps/cart/Dockerfile
      target: development
    ports:
      - '3004:3004'
    env_file:
      - ./apps/order/.env
    depends_on:
      - rabbitmq
      - mongodb-primary
      - users
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev cart

volumes:
  mongodb_master_data:
    driver: local # Define a custom network for MongoDB