apiVersion: v1
kind: Secret
metadata:
  name: microservice-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA== # base64 encoded "root"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM= # base64 encoded "password123"
