apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: akin2003/pick-cee:auth
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: microservices-config
            - secretRef:
                name: microservice-secret
          # volumeMounts:
          #   - name: app-volume
          #     mountPath: /usr/src/app
      # volumes:
      #   - name: app-volume
      #     emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
