apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: akin2003/pick-cee:cart
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: cart-config
            - configMapRef:
                name: auth-config
            - secretRef:
                name: microservice-secret
          resources:
            limits:
              cpu: '2'
              memory: '1Gi'
            requests:
              cpu: '1'
              memory: '512Mi'
          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 3001
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 3001
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
